# Generated by Django 3.1.8 on 2022-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointments_clinic_doctor_patients_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
