# Generated by Django 3.1.8 on 2022-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220110_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
