# Generated by Django 3.1.8 on 2022-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_patients_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='status',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
